# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/someone/University/labp/Kanban-board

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/someone/University/labp/Kanban-board

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/someone/University/labp/Kanban-board/CMakeFiles /home/someone/University/labp/Kanban-board//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/someone/University/labp/Kanban-board/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Kanban_board

# Build rule for target.
Kanban_board: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Kanban_board
.PHONY : Kanban_board

# fast build rule for target.
Kanban_board/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/build
.PHONY : Kanban_board/fast

card.o: card.c.o

.PHONY : card.o

# target to build an object file
card.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/card.c.o
.PHONY : card.c.o

card.i: card.c.i

.PHONY : card.i

# target to preprocess a source file
card.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/card.c.i
.PHONY : card.c.i

card.s: card.c.s

.PHONY : card.s

# target to generate assembly for a file
card.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/card.c.s
.PHONY : card.c.s

core.o: core.c.o

.PHONY : core.o

# target to build an object file
core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/core.c.o
.PHONY : core.c.o

core.i: core.c.i

.PHONY : core.i

# target to preprocess a source file
core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/core.c.i
.PHONY : core.c.i

core.s: core.c.s

.PHONY : core.s

# target to generate assembly for a file
core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/core.c.s
.PHONY : core.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/main.c.s
.PHONY : main.c.s

old_render.o: old_render.c.o

.PHONY : old_render.o

# target to build an object file
old_render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/old_render.c.o
.PHONY : old_render.c.o

old_render.i: old_render.c.i

.PHONY : old_render.i

# target to preprocess a source file
old_render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/old_render.c.i
.PHONY : old_render.c.i

old_render.s: old_render.c.s

.PHONY : old_render.s

# target to generate assembly for a file
old_render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/old_render.c.s
.PHONY : old_render.c.s

read.o: read.c.o

.PHONY : read.o

# target to build an object file
read.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/read.c.o
.PHONY : read.c.o

read.i: read.c.i

.PHONY : read.i

# target to preprocess a source file
read.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/read.c.i
.PHONY : read.c.i

read.s: read.c.s

.PHONY : read.s

# target to generate assembly for a file
read.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/read.c.s
.PHONY : read.c.s

render.o: render.c.o

.PHONY : render.o

# target to build an object file
render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/render.c.o
.PHONY : render.c.o

render.i: render.c.i

.PHONY : render.i

# target to preprocess a source file
render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/render.c.i
.PHONY : render.c.i

render.s: render.c.s

.PHONY : render.s

# target to generate assembly for a file
render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/render.c.s
.PHONY : render.c.s

tasklist.o: tasklist.c.o

.PHONY : tasklist.o

# target to build an object file
tasklist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/tasklist.c.o
.PHONY : tasklist.c.o

tasklist.i: tasklist.c.i

.PHONY : tasklist.i

# target to preprocess a source file
tasklist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/tasklist.c.i
.PHONY : tasklist.c.i

tasklist.s: tasklist.c.s

.PHONY : tasklist.s

# target to generate assembly for a file
tasklist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Kanban_board.dir/build.make CMakeFiles/Kanban_board.dir/tasklist.c.s
.PHONY : tasklist.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Kanban_board"
	@echo "... card.o"
	@echo "... card.i"
	@echo "... card.s"
	@echo "... core.o"
	@echo "... core.i"
	@echo "... core.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... old_render.o"
	@echo "... old_render.i"
	@echo "... old_render.s"
	@echo "... read.o"
	@echo "... read.i"
	@echo "... read.s"
	@echo "... render.o"
	@echo "... render.i"
	@echo "... render.s"
	@echo "... tasklist.o"
	@echo "... tasklist.i"
	@echo "... tasklist.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

